[tool.poetry]
name = "taskmanager"
version = "0.1.0"
description = ""
authors = ["daniil_gyrman0909 <gyrman01app@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^7.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
